### ISSUE TITLE
The original author is COMPLETELY uncredited

### ISSUE THREAD

**Issue by bmwalters** [comedinha/Pointshop2-Lottery#2]
Nice.
https://github.com/LinMax/PointShop-Lottery

**Comment by comedinha** [comment]
I did based on her code and not create the readme, it will be properly credited.
My code still has some problems in the functioning and only worked in TTT for now

**Comment by bmwalters** [comment]
Good to know.

**Comment by comedinha** [comment]
Fixed.

**Comment by CanadianJeff** [comment]
https://github.com/LinMax/PointShop-Lottery/issues/4
